/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VendorNetworkRouteImport } from './routes/vendor-network'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as EligibilityRouteImport } from './routes/eligibility'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BnextAiRouteImport } from './routes/bnext-ai'
import { Route as AccessibilityRouteImport } from './routes/accessibility'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StoriesIndexRouteImport } from './routes/stories.index'
import { Route as StartIndexRouteImport } from './routes/start.index'
import { Route as InsightsIndexRouteImport } from './routes/insights.index'
import { Route as FieldGuidesIndexRouteImport } from './routes/field-guides.index'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as ApplyIndexRouteImport } from './routes/apply.index'
import { Route as AiInActionIndexRouteImport } from './routes/ai-in-action.index'
import { Route as VendorsApplyRouteImport } from './routes/vendors.apply'
import { Route as StartReadyToImplementRouteImport } from './routes/start.ready-to-implement'
import { Route as StartNewToAiRouteImport } from './routes/start.new-to-ai'
import { Route as StartExperimentingRouteImport } from './routes/start.experimenting'
import { Route as SectorsSectorRouteImport } from './routes/sectors.$sector'
import { Route as ReferralPartnerRouteImport } from './routes/referral.$partner'
import { Route as InsightsSlugRouteImport } from './routes/insights.$slug'
import { Route as FieldGuidesSlugRouteImport } from './routes/field-guides.$slug'
import { Route as EventsSlugRouteImport } from './routes/events.$slug'
import { Route as ApplyConfirmationRouteImport } from './routes/apply.confirmation'
import { Route as AiInActionSlugRouteImport } from './routes/ai-in-action.$slug'

const VendorNetworkRoute = VendorNetworkRouteImport.update({
  id: '/vendor-network',
  path: '/vendor-network',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const EligibilityRoute = EligibilityRouteImport.update({
  id: '/eligibility',
  path: '/eligibility',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BnextAiRoute = BnextAiRouteImport.update({
  id: '/bnext-ai',
  path: '/bnext-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesIndexRoute = StoriesIndexRouteImport.update({
  id: '/stories/',
  path: '/stories/',
  getParentRoute: () => rootRouteImport,
} as any)
const StartIndexRoute = StartIndexRouteImport.update({
  id: '/start/',
  path: '/start/',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsIndexRoute = InsightsIndexRouteImport.update({
  id: '/insights/',
  path: '/insights/',
  getParentRoute: () => rootRouteImport,
} as any)
const FieldGuidesIndexRoute = FieldGuidesIndexRouteImport.update({
  id: '/field-guides/',
  path: '/field-guides/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyIndexRoute = ApplyIndexRouteImport.update({
  id: '/apply/',
  path: '/apply/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiInActionIndexRoute = AiInActionIndexRouteImport.update({
  id: '/ai-in-action/',
  path: '/ai-in-action/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorsApplyRoute = VendorsApplyRouteImport.update({
  id: '/vendors/apply',
  path: '/vendors/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const StartReadyToImplementRoute = StartReadyToImplementRouteImport.update({
  id: '/start/ready-to-implement',
  path: '/start/ready-to-implement',
  getParentRoute: () => rootRouteImport,
} as any)
const StartNewToAiRoute = StartNewToAiRouteImport.update({
  id: '/start/new-to-ai',
  path: '/start/new-to-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const StartExperimentingRoute = StartExperimentingRouteImport.update({
  id: '/start/experimenting',
  path: '/start/experimenting',
  getParentRoute: () => rootRouteImport,
} as any)
const SectorsSectorRoute = SectorsSectorRouteImport.update({
  id: '/sectors/$sector',
  path: '/sectors/$sector',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralPartnerRoute = ReferralPartnerRouteImport.update({
  id: '/referral/$partner',
  path: '/referral/$partner',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsSlugRoute = InsightsSlugRouteImport.update({
  id: '/insights/$slug',
  path: '/insights/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FieldGuidesSlugRoute = FieldGuidesSlugRouteImport.update({
  id: '/field-guides/$slug',
  path: '/field-guides/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/events/$slug',
  path: '/events/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyConfirmationRoute = ApplyConfirmationRouteImport.update({
  id: '/apply/confirmation',
  path: '/apply/confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const AiInActionSlugRoute = AiInActionSlugRouteImport.update({
  id: '/ai-in-action/$slug',
  path: '/ai-in-action/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/bnext-ai': typeof BnextAiRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/eligibility': typeof EligibilityRoute
  '/how-it-works': typeof HowItWorksRoute
  '/partners': typeof PartnersRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/vendor-network': typeof VendorNetworkRoute
  '/ai-in-action/$slug': typeof AiInActionSlugRoute
  '/apply/confirmation': typeof ApplyConfirmationRoute
  '/events/$slug': typeof EventsSlugRoute
  '/field-guides/$slug': typeof FieldGuidesSlugRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/referral/$partner': typeof ReferralPartnerRoute
  '/sectors/$sector': typeof SectorsSectorRoute
  '/start/experimenting': typeof StartExperimentingRoute
  '/start/new-to-ai': typeof StartNewToAiRoute
  '/start/ready-to-implement': typeof StartReadyToImplementRoute
  '/vendors/apply': typeof VendorsApplyRoute
  '/ai-in-action/': typeof AiInActionIndexRoute
  '/apply/': typeof ApplyIndexRoute
  '/events/': typeof EventsIndexRoute
  '/field-guides/': typeof FieldGuidesIndexRoute
  '/insights/': typeof InsightsIndexRoute
  '/start/': typeof StartIndexRoute
  '/stories/': typeof StoriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/bnext-ai': typeof BnextAiRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/eligibility': typeof EligibilityRoute
  '/how-it-works': typeof HowItWorksRoute
  '/partners': typeof PartnersRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/vendor-network': typeof VendorNetworkRoute
  '/ai-in-action/$slug': typeof AiInActionSlugRoute
  '/apply/confirmation': typeof ApplyConfirmationRoute
  '/events/$slug': typeof EventsSlugRoute
  '/field-guides/$slug': typeof FieldGuidesSlugRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/referral/$partner': typeof ReferralPartnerRoute
  '/sectors/$sector': typeof SectorsSectorRoute
  '/start/experimenting': typeof StartExperimentingRoute
  '/start/new-to-ai': typeof StartNewToAiRoute
  '/start/ready-to-implement': typeof StartReadyToImplementRoute
  '/vendors/apply': typeof VendorsApplyRoute
  '/ai-in-action': typeof AiInActionIndexRoute
  '/apply': typeof ApplyIndexRoute
  '/events': typeof EventsIndexRoute
  '/field-guides': typeof FieldGuidesIndexRoute
  '/insights': typeof InsightsIndexRoute
  '/start': typeof StartIndexRoute
  '/stories': typeof StoriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/bnext-ai': typeof BnextAiRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/eligibility': typeof EligibilityRoute
  '/how-it-works': typeof HowItWorksRoute
  '/partners': typeof PartnersRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/vendor-network': typeof VendorNetworkRoute
  '/ai-in-action/$slug': typeof AiInActionSlugRoute
  '/apply/confirmation': typeof ApplyConfirmationRoute
  '/events/$slug': typeof EventsSlugRoute
  '/field-guides/$slug': typeof FieldGuidesSlugRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/referral/$partner': typeof ReferralPartnerRoute
  '/sectors/$sector': typeof SectorsSectorRoute
  '/start/experimenting': typeof StartExperimentingRoute
  '/start/new-to-ai': typeof StartNewToAiRoute
  '/start/ready-to-implement': typeof StartReadyToImplementRoute
  '/vendors/apply': typeof VendorsApplyRoute
  '/ai-in-action/': typeof AiInActionIndexRoute
  '/apply/': typeof ApplyIndexRoute
  '/events/': typeof EventsIndexRoute
  '/field-guides/': typeof FieldGuidesIndexRoute
  '/insights/': typeof InsightsIndexRoute
  '/start/': typeof StartIndexRoute
  '/stories/': typeof StoriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/accessibility'
    | '/bnext-ai'
    | '/contact'
    | '/cookies'
    | '/eligibility'
    | '/how-it-works'
    | '/partners'
    | '/privacy'
    | '/resources'
    | '/search'
    | '/sitemap.xml'
    | '/terms'
    | '/vendor-network'
    | '/ai-in-action/$slug'
    | '/apply/confirmation'
    | '/events/$slug'
    | '/field-guides/$slug'
    | '/insights/$slug'
    | '/referral/$partner'
    | '/sectors/$sector'
    | '/start/experimenting'
    | '/start/new-to-ai'
    | '/start/ready-to-implement'
    | '/vendors/apply'
    | '/ai-in-action/'
    | '/apply/'
    | '/events/'
    | '/field-guides/'
    | '/insights/'
    | '/start/'
    | '/stories/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/accessibility'
    | '/bnext-ai'
    | '/contact'
    | '/cookies'
    | '/eligibility'
    | '/how-it-works'
    | '/partners'
    | '/privacy'
    | '/resources'
    | '/search'
    | '/sitemap.xml'
    | '/terms'
    | '/vendor-network'
    | '/ai-in-action/$slug'
    | '/apply/confirmation'
    | '/events/$slug'
    | '/field-guides/$slug'
    | '/insights/$slug'
    | '/referral/$partner'
    | '/sectors/$sector'
    | '/start/experimenting'
    | '/start/new-to-ai'
    | '/start/ready-to-implement'
    | '/vendors/apply'
    | '/ai-in-action'
    | '/apply'
    | '/events'
    | '/field-guides'
    | '/insights'
    | '/start'
    | '/stories'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/accessibility'
    | '/bnext-ai'
    | '/contact'
    | '/cookies'
    | '/eligibility'
    | '/how-it-works'
    | '/partners'
    | '/privacy'
    | '/resources'
    | '/search'
    | '/sitemap.xml'
    | '/terms'
    | '/vendor-network'
    | '/ai-in-action/$slug'
    | '/apply/confirmation'
    | '/events/$slug'
    | '/field-guides/$slug'
    | '/insights/$slug'
    | '/referral/$partner'
    | '/sectors/$sector'
    | '/start/experimenting'
    | '/start/new-to-ai'
    | '/start/ready-to-implement'
    | '/vendors/apply'
    | '/ai-in-action/'
    | '/apply/'
    | '/events/'
    | '/field-guides/'
    | '/insights/'
    | '/start/'
    | '/stories/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccessibilityRoute: typeof AccessibilityRoute
  BnextAiRoute: typeof BnextAiRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  EligibilityRoute: typeof EligibilityRoute
  HowItWorksRoute: typeof HowItWorksRoute
  PartnersRoute: typeof PartnersRoute
  PrivacyRoute: typeof PrivacyRoute
  ResourcesRoute: typeof ResourcesRoute
  SearchRoute: typeof SearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  VendorNetworkRoute: typeof VendorNetworkRoute
  AiInActionSlugRoute: typeof AiInActionSlugRoute
  ApplyConfirmationRoute: typeof ApplyConfirmationRoute
  EventsSlugRoute: typeof EventsSlugRoute
  FieldGuidesSlugRoute: typeof FieldGuidesSlugRoute
  InsightsSlugRoute: typeof InsightsSlugRoute
  ReferralPartnerRoute: typeof ReferralPartnerRoute
  SectorsSectorRoute: typeof SectorsSectorRoute
  StartExperimentingRoute: typeof StartExperimentingRoute
  StartNewToAiRoute: typeof StartNewToAiRoute
  StartReadyToImplementRoute: typeof StartReadyToImplementRoute
  VendorsApplyRoute: typeof VendorsApplyRoute
  AiInActionIndexRoute: typeof AiInActionIndexRoute
  ApplyIndexRoute: typeof ApplyIndexRoute
  EventsIndexRoute: typeof EventsIndexRoute
  FieldGuidesIndexRoute: typeof FieldGuidesIndexRoute
  InsightsIndexRoute: typeof InsightsIndexRoute
  StartIndexRoute: typeof StartIndexRoute
  StoriesIndexRoute: typeof StoriesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vendor-network': {
      id: '/vendor-network'
      path: '/vendor-network'
      fullPath: '/vendor-network'
      preLoaderRoute: typeof VendorNetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eligibility': {
      id: '/eligibility'
      path: '/eligibility'
      fullPath: '/eligibility'
      preLoaderRoute: typeof EligibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bnext-ai': {
      id: '/bnext-ai'
      path: '/bnext-ai'
      fullPath: '/bnext-ai'
      preLoaderRoute: typeof BnextAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/': {
      id: '/stories/'
      path: '/stories'
      fullPath: '/stories/'
      preLoaderRoute: typeof StoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start/': {
      id: '/start/'
      path: '/start'
      fullPath: '/start/'
      preLoaderRoute: typeof StartIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/': {
      id: '/insights/'
      path: '/insights'
      fullPath: '/insights/'
      preLoaderRoute: typeof InsightsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/field-guides/': {
      id: '/field-guides/'
      path: '/field-guides'
      fullPath: '/field-guides/'
      preLoaderRoute: typeof FieldGuidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply/': {
      id: '/apply/'
      path: '/apply'
      fullPath: '/apply/'
      preLoaderRoute: typeof ApplyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-in-action/': {
      id: '/ai-in-action/'
      path: '/ai-in-action'
      fullPath: '/ai-in-action/'
      preLoaderRoute: typeof AiInActionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendors/apply': {
      id: '/vendors/apply'
      path: '/vendors/apply'
      fullPath: '/vendors/apply'
      preLoaderRoute: typeof VendorsApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start/ready-to-implement': {
      id: '/start/ready-to-implement'
      path: '/start/ready-to-implement'
      fullPath: '/start/ready-to-implement'
      preLoaderRoute: typeof StartReadyToImplementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start/new-to-ai': {
      id: '/start/new-to-ai'
      path: '/start/new-to-ai'
      fullPath: '/start/new-to-ai'
      preLoaderRoute: typeof StartNewToAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start/experimenting': {
      id: '/start/experimenting'
      path: '/start/experimenting'
      fullPath: '/start/experimenting'
      preLoaderRoute: typeof StartExperimentingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sectors/$sector': {
      id: '/sectors/$sector'
      path: '/sectors/$sector'
      fullPath: '/sectors/$sector'
      preLoaderRoute: typeof SectorsSectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referral/$partner': {
      id: '/referral/$partner'
      path: '/referral/$partner'
      fullPath: '/referral/$partner'
      preLoaderRoute: typeof ReferralPartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/$slug': {
      id: '/insights/$slug'
      path: '/insights/$slug'
      fullPath: '/insights/$slug'
      preLoaderRoute: typeof InsightsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/field-guides/$slug': {
      id: '/field-guides/$slug'
      path: '/field-guides/$slug'
      fullPath: '/field-guides/$slug'
      preLoaderRoute: typeof FieldGuidesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/events/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply/confirmation': {
      id: '/apply/confirmation'
      path: '/apply/confirmation'
      fullPath: '/apply/confirmation'
      preLoaderRoute: typeof ApplyConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-in-action/$slug': {
      id: '/ai-in-action/$slug'
      path: '/ai-in-action/$slug'
      fullPath: '/ai-in-action/$slug'
      preLoaderRoute: typeof AiInActionSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccessibilityRoute: AccessibilityRoute,
  BnextAiRoute: BnextAiRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  EligibilityRoute: EligibilityRoute,
  HowItWorksRoute: HowItWorksRoute,
  PartnersRoute: PartnersRoute,
  PrivacyRoute: PrivacyRoute,
  ResourcesRoute: ResourcesRoute,
  SearchRoute: SearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  VendorNetworkRoute: VendorNetworkRoute,
  AiInActionSlugRoute: AiInActionSlugRoute,
  ApplyConfirmationRoute: ApplyConfirmationRoute,
  EventsSlugRoute: EventsSlugRoute,
  FieldGuidesSlugRoute: FieldGuidesSlugRoute,
  InsightsSlugRoute: InsightsSlugRoute,
  ReferralPartnerRoute: ReferralPartnerRoute,
  SectorsSectorRoute: SectorsSectorRoute,
  StartExperimentingRoute: StartExperimentingRoute,
  StartNewToAiRoute: StartNewToAiRoute,
  StartReadyToImplementRoute: StartReadyToImplementRoute,
  VendorsApplyRoute: VendorsApplyRoute,
  AiInActionIndexRoute: AiInActionIndexRoute,
  ApplyIndexRoute: ApplyIndexRoute,
  EventsIndexRoute: EventsIndexRoute,
  FieldGuidesIndexRoute: FieldGuidesIndexRoute,
  InsightsIndexRoute: InsightsIndexRoute,
  StartIndexRoute: StartIndexRoute,
  StoriesIndexRoute: StoriesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
