/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as BnextAiRouteImport } from './routes/bnext-ai'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StartIndexRouteImport } from './routes/start.index'
import { Route as StartReadyToImplementRouteImport } from './routes/start.ready-to-implement'
import { Route as StartNewToAiRouteImport } from './routes/start.new-to-ai'
import { Route as StartExperimentingRouteImport } from './routes/start.experimenting'

const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const BnextAiRoute = BnextAiRouteImport.update({
  id: '/bnext-ai',
  path: '/bnext-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StartIndexRoute = StartIndexRouteImport.update({
  id: '/start/',
  path: '/start/',
  getParentRoute: () => rootRouteImport,
} as any)
const StartReadyToImplementRoute = StartReadyToImplementRouteImport.update({
  id: '/start/ready-to-implement',
  path: '/start/ready-to-implement',
  getParentRoute: () => rootRouteImport,
} as any)
const StartNewToAiRoute = StartNewToAiRouteImport.update({
  id: '/start/new-to-ai',
  path: '/start/new-to-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const StartExperimentingRoute = StartExperimentingRouteImport.update({
  id: '/start/experimenting',
  path: '/start/experimenting',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bnext-ai': typeof BnextAiRoute
  '/how-it-works': typeof HowItWorksRoute
  '/start/experimenting': typeof StartExperimentingRoute
  '/start/new-to-ai': typeof StartNewToAiRoute
  '/start/ready-to-implement': typeof StartReadyToImplementRoute
  '/start/': typeof StartIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bnext-ai': typeof BnextAiRoute
  '/how-it-works': typeof HowItWorksRoute
  '/start/experimenting': typeof StartExperimentingRoute
  '/start/new-to-ai': typeof StartNewToAiRoute
  '/start/ready-to-implement': typeof StartReadyToImplementRoute
  '/start': typeof StartIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bnext-ai': typeof BnextAiRoute
  '/how-it-works': typeof HowItWorksRoute
  '/start/experimenting': typeof StartExperimentingRoute
  '/start/new-to-ai': typeof StartNewToAiRoute
  '/start/ready-to-implement': typeof StartReadyToImplementRoute
  '/start/': typeof StartIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bnext-ai'
    | '/how-it-works'
    | '/start/experimenting'
    | '/start/new-to-ai'
    | '/start/ready-to-implement'
    | '/start/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bnext-ai'
    | '/how-it-works'
    | '/start/experimenting'
    | '/start/new-to-ai'
    | '/start/ready-to-implement'
    | '/start'
  id:
    | '__root__'
    | '/'
    | '/bnext-ai'
    | '/how-it-works'
    | '/start/experimenting'
    | '/start/new-to-ai'
    | '/start/ready-to-implement'
    | '/start/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BnextAiRoute: typeof BnextAiRoute
  HowItWorksRoute: typeof HowItWorksRoute
  StartExperimentingRoute: typeof StartExperimentingRoute
  StartNewToAiRoute: typeof StartNewToAiRoute
  StartReadyToImplementRoute: typeof StartReadyToImplementRoute
  StartIndexRoute: typeof StartIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bnext-ai': {
      id: '/bnext-ai'
      path: '/bnext-ai'
      fullPath: '/bnext-ai'
      preLoaderRoute: typeof BnextAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start/': {
      id: '/start/'
      path: '/start'
      fullPath: '/start/'
      preLoaderRoute: typeof StartIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start/ready-to-implement': {
      id: '/start/ready-to-implement'
      path: '/start/ready-to-implement'
      fullPath: '/start/ready-to-implement'
      preLoaderRoute: typeof StartReadyToImplementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start/new-to-ai': {
      id: '/start/new-to-ai'
      path: '/start/new-to-ai'
      fullPath: '/start/new-to-ai'
      preLoaderRoute: typeof StartNewToAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start/experimenting': {
      id: '/start/experimenting'
      path: '/start/experimenting'
      fullPath: '/start/experimenting'
      preLoaderRoute: typeof StartExperimentingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BnextAiRoute: BnextAiRoute,
  HowItWorksRoute: HowItWorksRoute,
  StartExperimentingRoute: StartExperimentingRoute,
  StartNewToAiRoute: StartNewToAiRoute,
  StartReadyToImplementRoute: StartReadyToImplementRoute,
  StartIndexRoute: StartIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
